@startuml
!include style.puml

title OORMS:\nSequence Diagrams #2 \nItem Cancel - notify_views() \n

participant "controller:\nOrderController" as order_controller
participant "restaurant:\nRestaurant" as restaurant
participant "view[0]:\nServerView" as server_view
participant "restaurant_controller:\nRestaurantController" as restaurant_controller
participant "view[1]:\nKitchenView" as kitchen_view
participant "kitchen_controller:\nKitchenController" as kitchen_controller


order_controller -> restaurant : notify_views()

restaurant -> server_view : update()

server_view -> restaurant_controller : create_ui()

restaurant_controller -> server_view : create_restaurant_ui()

restaurant -> kitchen_view : update()

kitchen_view -> kitchen_controller : create_ui()

kitchen_controller -> kitchen_view : create_kitchen_order_ui()



@enduml