@startuml
!include style.puml

title OORMS:\nSequence Diagrams #2\nItem Cancel [X] Button Pressed
actor Server as server

participant "view:\nServerView" as view
participant "controller:\nOrderController" as controller
participant "order:\nOrder" as order
participant "items:\nOrderItems" as items
participant "restaurant:\nRestaurant" as rest
participant "views:\nRestaurantViews" as views


server -> view : [X] button is pressed
view -> controller : remove_spec_item(cancelled_item)
controller -> order : remove_item(cancelled_item)

order -> items : remove(cancelled_item)






controller -> rest : notify_views()

loop view in self.views
    rest -> views : view.update()
end

@enduml