@startuml
!include style.puml

'autonumber

title Withdrawal\n**Design** Sequence Diagram\n

actor Client as client
participant ":UserInterface" as atm
participant ":CardReader" as cr
participant "clients:\nClientList" as clients
participant "c:\nClientRecord" as c
participant "a:\nAccount" as a
participant "accounts:\nList[Account]" as accounts
participant "chequing:\nAccount" as chequing
participant "withdrawal:\nTransaction" as wdr
participant ":Ledger" as ledger

client -> atm ++: insert card
atm --> client --: request PIN
client -> atm ++: enters PIN
atm -> cr : client_no = validate(PIN)
atm -> clients: c = find(client_no)
atm -> c : tr = retrieve_transactions()

atm --> client --: show possible transactions
client -> atm ++: withdrawal
atm -> c : accounts = retrieve_accounts()
loop a in accounts
    atm -> a : name = get_name()
    atm --> client-- : display name
end


client -> atm ++: chequing
atm -> accounts : chequing = get_account(chequing)
atm -> chequing : balance = get_balance()
atm --> client --: display balance, request amount

client -> atm ++: enter amount
atm -> chequing ++ : withdrawal = withdraw(amount)
chequing -> chequing : balance -= amount
chequing -> wdr ** : (chequing, amount, balance)
deactivate
atm -> wdr : balance = get_balance()
atm --> client --: display balance, return card

client -> atm ++: take card
atm -> atm : print_receipt()
atm --> client : dispense cash and receipt
atm -> wdr ++ : commit()
wdr -> ledger --: commit(wdr)
deactivate

client -> atm ++: take cash and receipt
atm --> client --: display welcome screen

@enduml